<?php

declare(strict_types=1);

namespace OsfSeo\Database;

/**
 * Oczekiwany (najnowszy) stan schematu — źródło prawdy dla `wp osf-seo db:status` i testów.
 *
 * Celowo niezależny od DDL migracji: test integracyjny sprawdza, że świeża instalacja
 * przez migracje daje dokładnie ten stan (wykrywa rozjazd migracji i specyfikacji).
 * Przy każdej nowej migracji zmieniającej schemat zaktualizuj także ten opis.
 *
 * Typy kolumn w postaci znormalizowanej (małe litery, bez szerokości wyświetlania intów).
 */
final class Schema
{
	/**
	 * @return array<string, array{
	 *     columns: array<string, string>,
	 *     primary: list<string>,
	 *     unique: array<string, list<string>>,
	 *     indexes: array<string, list<string>>,
	 * }>
	 */
	public static function tables(): array
	{
		$metrics = [
			'clicks' => 'int unsigned',
			'impressions' => 'int unsigned',
			'position_sum' => 'double',
		];

		return [
			'projects' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'name' => 'varchar(190)',
					'domain' => 'varchar(190)',
					'country' => 'char(2)',
					'language' => 'varchar(10)',
					'status' => "enum('active','paused','archived')",
					'connection_id' => 'int unsigned',
					'gsc_property' => 'varchar(255)',
					'gsc_permission' => 'varchar(32)',
					'gsc_data_property' => 'varchar(255)',
					'settings' => 'longtext',
					'last_synced_at' => 'datetime',
					'created_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id']],
				'indexes' => ['status' => ['status'], 'domain' => ['domain'], 'connection_id' => ['connection_id']],
			],
			'project_users' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'user_id' => 'bigint unsigned',
					'role' => "enum('manager','viewer')",
					'created_at' => 'datetime',
				],
				'primary' => ['project_id', 'user_id'],
				'unique' => [],
				'indexes' => ['user_project' => ['user_id', 'project_id']],
			],
			'connections' => [
				'columns' => [
					'id' => 'int unsigned',
					'owner_user_id' => 'bigint unsigned',
					'provider' => 'varchar(20)',
					'google_sub' => 'varchar(255)',
					'email' => 'varchar(190)',
					'refresh_token_enc' => 'text',
					'scopes' => 'text',
					'status' => "enum('active','needs_reauth','revoked')",
					'last_error' => 'varchar(255)',
					'last_refreshed_at' => 'datetime',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['provider_account_owner' => ['provider', 'google_sub', 'owner_user_id']],
				'indexes' => ['owner_user_id' => ['owner_user_id']],
			],
			'keywords' => [
				'columns' => [
					'id' => 'int unsigned',
					'project_id' => 'int unsigned',
					'keyword' => 'varchar(500)',
					'keyword_hash' => 'binary(16)',
					'first_seen' => 'date',
					'last_seen' => 'date',
					'created_at' => 'datetime',
					'market_key' => 'binary(16)',
				],
				'primary' => ['id'],
				'unique' => ['project_keyword_hash' => ['project_id', 'keyword_hash']],
				'indexes' => ['project_last_seen' => ['project_id', 'last_seen'], 'project_market_key' => ['project_id', 'market_key']],
			],
			'pages' => [
				'columns' => [
					'id' => 'int unsigned',
					'project_id' => 'int unsigned',
					'url' => 'varchar(2048)',
					'url_hash' => 'binary(16)',
					'path' => 'varchar(2048)',
					'first_seen' => 'date',
					'last_seen' => 'date',
					'created_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['project_url_hash' => ['project_id', 'url_hash']],
				'indexes' => [],
			],
			'gsc_site_daily' => [
				'columns' => ['project_id' => 'int unsigned', 'date' => 'date', 'device' => 'tinyint unsigned'] + $metrics,
				'primary' => ['project_id', 'date', 'device'],
				'unique' => [],
				'indexes' => [],
			],
			'gsc_query_daily' => [
				'columns' => ['project_id' => 'int unsigned', 'date' => 'date', 'keyword_id' => 'int unsigned'] + $metrics,
				'primary' => ['project_id', 'date', 'keyword_id'],
				'unique' => [],
				'indexes' => ['project_keyword_date' => ['project_id', 'keyword_id', 'date']],
			],
			'gsc_query_page_daily' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'date' => 'date',
					'keyword_id' => 'int unsigned',
					'page_id' => 'int unsigned',
				] + $metrics,
				'primary' => ['project_id', 'date', 'keyword_id', 'page_id'],
				'unique' => [],
				'indexes' => [
					'project_keyword_date_page' => ['project_id', 'keyword_id', 'date', 'page_id'],
					'project_page_date_keyword' => ['project_id', 'page_id', 'date', 'keyword_id'],
				],
			],
			'gsc_import_staging' => [
				'columns' => [
					'run_id' => 'bigint unsigned',
					'date' => 'date',
					'keyword_id' => 'int unsigned',
					'page_id' => 'int unsigned',
				] + $metrics,
				'primary' => ['run_id', 'date', 'keyword_id', 'page_id'],
				'unique' => [],
				'indexes' => [],
			],
			'visibility_daily' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'date' => 'date',
					'top3' => 'int unsigned',
					'top10' => 'int unsigned',
					'top20' => 'int unsigned',
					'top50' => 'int unsigned',
					'top100' => 'int unsigned',
					'keywords_total' => 'int unsigned',
				],
				'primary' => ['project_id', 'date'],
				'unique' => [],
				'indexes' => [],
			],
			'sync_state' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'dataset' => 'varchar(32)',
					'status' => "enum('idle','queued','running','failed','retrying')",
					'newest_date' => 'date',
					'oldest_date' => 'date',
					'refresh_cursor' => 'date',
					'consecutive_failures' => 'smallint unsigned',
					'last_success_at' => 'datetime',
					'last_attempt_at' => 'datetime',
					'last_refresh_at' => 'datetime',
					'retry_after' => 'datetime',
					'last_error' => 'varchar(500)',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id', 'dataset'],
				'unique' => [],
				'indexes' => [],
			],
			'sync_runs' => [
				'columns' => [
					'id' => 'bigint unsigned',
					'project_id' => 'int unsigned',
					'dataset' => 'varchar(32)',
					'trigger_type' => "enum('schedule','manual','backfill','connect')",
					'window_start' => 'date',
					'window_end' => 'date',
					'status' => "enum('queued','running','success','failed','skipped','retrying','cancelled')",
					'priority' => 'tinyint unsigned',
					'attempt' => 'smallint unsigned',
					'rows_fetched' => 'int unsigned',
					'rows_written' => 'int unsigned',
					'api_requests' => 'smallint unsigned',
					'error_code' => 'varchar(64)',
					'error_message' => 'text',
					'queued_at' => 'datetime',
					'available_at' => 'datetime',
					'started_at' => 'datetime',
					'finished_at' => 'datetime',
					'locked_until' => 'datetime',
					'property' => 'varchar(255)',
				],
				'primary' => ['id'],
				'unique' => [],
				'indexes' => [
					'project_run' => ['project_id', 'id'],
					'status_queued' => ['status', 'queued_at'],
					'queue' => ['status', 'priority', 'available_at'],
					'project_dataset_status' => ['project_id', 'dataset', 'status'],
				],
			],
			'opportunities' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'fingerprint' => 'binary(16)',
					'type' => 'varchar(32)',
					'property' => 'varchar(255)',
					'page_url' => 'varchar(2048)',
					'page_hash' => 'binary(16)',
					'keyword' => 'varchar(500)',
					'state' => "enum('active','inactive','archived')",
					'status' => "enum('new','review','planned','in_progress','completed','dismissed')",
					'note' => 'text',
					'completed_on' => 'date',
					'baseline' => 'longtext',
					'last_priority' => 'tinyint unsigned',
					'last_confidence' => 'tinyint unsigned',
					'last_period_days' => 'tinyint unsigned',
					'last_latest_date' => 'date',
					'last_evidence' => 'longtext',
					'first_detected_at' => 'datetime',
					'last_detected_at' => 'datetime',
					'inactive_since' => 'datetime',
					'status_changed_at' => 'datetime',
					'status_changed_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_fingerprint' => ['project_id', 'fingerprint']],
				'indexes' => ['project_state_status' => ['project_id', 'state', 'status'], 'project_page' => ['project_id', 'page_hash']],
			],
			'opportunity_detections' => [
				'columns' => [
					'opportunity_id' => 'int unsigned',
					'period_days' => 'tinyint unsigned',
					'project_id' => 'int unsigned',
					'priority' => 'tinyint unsigned',
					'confidence' => 'tinyint unsigned',
					'impressions' => 'int unsigned',
					'clicks' => 'int unsigned',
					'latest_date' => 'date',
					'search_text' => 'text',
					'evidence' => 'longtext',
					'analyzed_at' => 'datetime',
				],
				'primary' => ['opportunity_id', 'period_days'],
				'unique' => [],
				'indexes' => ['project_period_priority' => ['project_id', 'period_days', 'priority']],
			],
			'opportunity_analyses' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'period_days' => 'tinyint unsigned',
					'status' => "enum('success','skipped','failed')",
					'trigger_type' => 'varchar(16)',
					'property' => 'varchar(255)',
					'data_key' => 'char(32)',
					'latest_date' => 'date',
					'opportunities' => 'int unsigned',
					'duration_ms' => 'int unsigned',
					'message' => 'varchar(255)',
					'analyzed_at' => 'datetime',
				],
				'primary' => ['project_id', 'period_days'],
				'unique' => [],
				'indexes' => [],
			],
			'market_keywords' => [
				'columns' => [
					'id' => 'int unsigned',
					'provider' => 'varchar(20)',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'keyword_key' => 'binary(16)',
					'keyword' => 'varchar(255)',
					'search_volume' => 'int unsigned',
					'cpc' => 'decimal(12,4)',
					'competition_level' => 'varchar(16)',
					'competition_index' => 'tinyint unsigned',
					'low_top_of_page_bid' => 'decimal(12,4)',
					'high_top_of_page_bid' => 'decimal(12,4)',
					'keyword_difficulty' => 'tinyint unsigned',
					'volume_fetched_at' => 'datetime',
					'volume_stale_after' => 'datetime',
					'volume_pending_until' => 'datetime',
					'volume_task_id' => 'bigint unsigned',
					'difficulty_fetched_at' => 'datetime',
					'difficulty_stale_after' => 'datetime',
					'difficulty_task_id' => 'bigint unsigned',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
					'search_intent' => 'varchar(16)',
					'intent_fetched_at' => 'datetime',
					'core_key' => 'binary(16)',
				],
				'primary' => ['id'],
				'unique' => ['market_keyword' => ['provider', 'location_code', 'language_code', 'keyword_key']],
				'indexes' => [],
			],
			'market_keyword_monthly' => [
				'columns' => [
					'market_keyword_id' => 'int unsigned',
					'month' => 'date',
					'search_volume' => 'int unsigned',
					'updated_at' => 'datetime',
				],
				'primary' => ['market_keyword_id', 'month'],
				'unique' => [],
				'indexes' => [],
			],
			'market_tasks' => [
				'columns' => [
					'id' => 'bigint unsigned',
					'provider' => 'varchar(20)',
					'endpoint' => 'varchar(64)',
					'mode' => "enum('standard','live')",
					'trigger_type' => 'varchar(16)',
					'project_id' => 'int unsigned',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'provider_task_id' => 'varchar(64)',
					'status' => "enum('pending','completed','failed','expired')",
					'keywords_count' => 'int unsigned',
					'results_count' => 'int unsigned',
					'keywords' => 'longtext',
					'estimated_cost' => 'decimal(12,6)',
					'cost' => 'decimal(12,6)',
					'attempts' => 'smallint unsigned',
					'error_code' => 'varchar(64)',
					'error_message' => 'varchar(255)',
					'created_at' => 'datetime',
					'next_check_at' => 'datetime',
					'completed_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => [],
				'indexes' => [
					'status_check' => ['status', 'next_check_at'],
					'created' => ['created_at'],
					'project_task' => ['project_id', 'id'],
				],
			],
			'market_sync_state' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'provider' => 'varchar(20)',
					'enabled_at' => 'datetime',
					'enabled_by' => 'bigint unsigned',
					'last_run_at' => 'datetime',
					'last_success_at' => 'datetime',
					'last_error' => 'varchar(64)',
					'last_error_at' => 'datetime',
					'next_auto_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id', 'provider'],
				'unique' => [],
				'indexes' => [],
			],
			'discovery_runs' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'provider' => 'varchar(20)',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'method' => 'varchar(16)',
					'depth' => 'tinyint unsigned',
					'status' => "enum('queued','running','completed','partial','failed','cancelled')",
					'trigger_type' => 'varchar(16)',
					'seeds_count' => 'smallint unsigned',
					'max_candidates' => 'smallint unsigned',
					'seed_limit' => 'smallint unsigned',
					'min_volume' => 'int unsigned',
					'max_difficulty' => 'tinyint unsigned',
					'forced' => 'tinyint unsigned',
					'options' => 'longtext',
					'tasks_planned' => 'smallint unsigned',
					'tasks_done' => 'smallint unsigned',
					'estimated_cost' => 'decimal(12,6)',
					'cost' => 'decimal(12,6)',
					'items_received' => 'int unsigned',
					'candidates_new' => 'int unsigned',
					'candidates_seen' => 'int unsigned',
					'rejected' => 'longtext',
					'blocked_by' => 'varchar(32)',
					'error_code' => 'varchar(64)',
					'error_message' => 'varchar(255)',
					'created_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'started_at' => 'datetime',
					'finished_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id']],
				'indexes' => ['project_run' => ['project_id', 'id'], 'status_run' => ['status', 'id']],
			],
			'discovery_run_seeds' => [
				'columns' => [
					'run_id' => 'int unsigned',
					'seed_key' => 'binary(16)',
					'seed' => 'varchar(255)',
					'source' => 'varchar(16)',
					'position' => 'smallint unsigned',
					'status' => "enum('pending','running','done','cached','failed','cancelled')",
					'pages_done' => 'tinyint unsigned',
					'next_offset' => 'int unsigned',
					'items' => 'int unsigned',
					'candidates_new' => 'int unsigned',
					'cost' => 'decimal(12,6)',
					'task_id' => 'bigint unsigned',
					'attempts' => 'tinyint unsigned',
					'error_code' => 'varchar(64)',
					'next_attempt_at' => 'datetime',
					'started_at' => 'datetime',
					'finished_at' => 'datetime',
				],
				'primary' => ['run_id', 'seed_key'],
				'unique' => [],
				'indexes' => [],
			],
			'discovery_candidates' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'status' => "enum('new','review','accepted','dismissed')",
					'note' => 'text',
					'status_changed_at' => 'datetime',
					'status_changed_by' => 'bigint unsigned',
					'seeds_count' => 'smallint unsigned',
					'best_relation' => 'tinyint unsigned',
					'visibility' => "enum('unknown','none','low','visible')",
					'gsc_impressions' => 'int unsigned',
					'gsc_clicks' => 'int unsigned',
					'gsc_position' => 'decimal(6,2)',
					'target_url' => 'varchar(2048)',
					'priority' => 'tinyint unsigned',
					'score' => 'longtext',
					'excluded' => 'tinyint unsigned',
					'provider_meta' => 'longtext',
					'first_run_id' => 'int unsigned',
					'last_run_id' => 'int unsigned',
					'discovered_at' => 'datetime',
					'last_seen_at' => 'datetime',
					'scored_at' => 'datetime',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_market_keyword' => ['project_id', 'market_keyword_id']],
				'indexes' => ['project_priority' => ['project_id', 'priority']],
			],
			'discovery_candidate_sources' => [
				'columns' => [
					'candidate_id' => 'int unsigned',
					'seed_key' => 'binary(16)',
					'method' => 'varchar(16)',
					'seed' => 'varchar(255)',
					'run_id' => 'int unsigned',
					'relation' => 'tinyint unsigned',
					'depth' => 'tinyint unsigned',
					'result_position' => 'smallint unsigned',
					'first_seen_at' => 'datetime',
					'last_seen_at' => 'datetime',
				],
				'primary' => ['candidate_id', 'seed_key', 'method'],
				'unique' => [],
				'indexes' => ['run' => ['run_id']],
			],
			'discovery_settings' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'excluded_terms' => 'text',
					'refresh_key' => 'char(32)',
					'refreshed_at' => 'datetime',
					'updated_by' => 'bigint unsigned',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id'],
				'unique' => [],
				'indexes' => [],
			],
			'serp_contexts' => [
				'columns' => [
					'id' => 'smallint unsigned',
					'context_key' => 'binary(16)',
					'engine' => 'varchar(16)',
					'serp_type' => 'varchar(16)',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'device' => 'varchar(16)',
					'os' => 'varchar(16)',
					'depth' => 'smallint unsigned',
					'created_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['context_key' => ['context_key']],
				'indexes' => [],
			],
			'serp_settings' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'enabled' => 'tinyint unsigned',
					'frequency' => "enum('daily','every_3_days','weekly')",
					'device' => "enum('desktop','mobile')",
					'depth' => 'smallint unsigned',
					'enabled_at' => 'datetime',
					'enabled_by' => 'bigint unsigned',
					'next_run_at' => 'datetime',
					'retry_after' => 'datetime',
					'last_run_at' => 'datetime',
					'last_skip_reason' => 'varchar(32)',
					'last_skip_at' => 'datetime',
					'updated_by' => 'bigint unsigned',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id'],
				'unique' => [],
				'indexes' => ['due' => ['enabled', 'next_run_at']],
			],
			'serp_competitors' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'name' => 'varchar(190)',
					'domain' => 'varchar(253)',
					'domain_key' => 'binary(16)',
					'status' => "enum('active','inactive','archived')",
					'created_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'updated_by' => 'bigint unsigned',
					'updated_at' => 'datetime',
					'brand_terms' => 'text',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_domain' => ['project_id', 'domain_key']],
				'indexes' => ['project_status' => ['project_id', 'status']],
			],
			'serp_tracked_keywords' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'source' => "enum('manual','gsc','discovery','gap')",
					'status' => "enum('active','removed')",
					'added_by' => 'bigint unsigned',
					'added_at' => 'datetime',
					'removed_at' => 'datetime',
					'last_requested_at' => 'datetime',
					'last_snapshot_id' => 'int unsigned',
					'last_context_id' => 'smallint unsigned',
					'last_checked_at' => 'datetime',
					'last_found' => 'tinyint unsigned',
					'last_rank' => 'smallint unsigned',
					'last_rank_absolute' => 'smallint unsigned',
					'last_url_id' => 'int unsigned',
					'last_depth' => 'smallint unsigned',
					'last_featured' => 'tinyint unsigned',
					'prev_snapshot_id' => 'int unsigned',
					'prev_found' => 'tinyint unsigned',
					'prev_rank' => 'smallint unsigned',
					'change_type' => "enum('new','up','down','same','entered','left','out','incomparable')",
					'change_value' => 'smallint',
					'top10_change' => "enum('entered','left')",
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_market_keyword' => ['project_id', 'market_keyword_id']],
				'indexes' => [
					'project_rank' => ['project_id', 'status', 'last_rank'],
					'project_requested' => ['project_id', 'status', 'last_requested_at'],
				],
			],
			'serp_runs' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'context_id' => 'smallint unsigned',
					'trigger_type' => "enum('schedule','manual')",
					'slot_key' => 'varchar(40)',
					'status' => "enum('queued','submitting','submitted','completed','partial','failed','skipped','cancelled')",
					'skip_reason' => 'varchar(32)',
					'keywords_planned' => 'int unsigned',
					'keywords_skipped' => 'int unsigned',
					'tasks_submitted' => 'int unsigned',
					'tasks_completed' => 'int unsigned',
					'tasks_failed' => 'int unsigned',
					'estimated_cost' => 'decimal(12,6)',
					'cost' => 'decimal(12,6)',
					'error_code' => 'varchar(64)',
					'error_message' => 'varchar(255)',
					'created_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'submitted_at' => 'datetime',
					'finished_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_slot' => ['project_id', 'slot_key']],
				'indexes' => ['project_run' => ['project_id', 'id'], 'status_run' => ['status', 'id']],
			],
			'serp_snapshots' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'tracked_keyword_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'context_id' => 'smallint unsigned',
					'run_id' => 'int unsigned',
					'market_task_id' => 'bigint unsigned',
					'provider' => 'varchar(20)',
					'provider_task_id' => 'varchar(64)',
					'status' => "enum('queued','uncertain','submitted','completed','failed','expired','cancelled')",
					'trigger_type' => "enum('schedule','manual')",
					'requested_depth' => 'smallint unsigned',
					'estimated_cost' => 'decimal(10,6)',
					'cost' => 'decimal(10,6)',
					'attempts' => 'tinyint unsigned',
					'error_code' => 'varchar(64)',
					'created_at' => 'datetime',
					'submitted_at' => 'datetime',
					'next_check_at' => 'datetime',
					'checked_at' => 'datetime',
					'collected_at' => 'datetime',
					'se_domain' => 'varchar(64)',
					'se_results_count' => 'bigint unsigned',
					'pages_count' => 'tinyint unsigned',
					'items_count' => 'smallint unsigned',
					'organic_count' => 'smallint unsigned',
					'item_types' => 'bigint unsigned',
					'spell_type' => 'varchar(32)',
					'spell_keyword' => 'varchar(255)',
					'project_rank' => 'smallint unsigned',
					'project_rank_absolute' => 'smallint unsigned',
					'project_url_id' => 'int unsigned',
					'project_results' => 'tinyint unsigned',
					'project_featured' => 'tinyint unsigned',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id']],
				'indexes' => [
					'tracked_history' => ['tracked_keyword_id', 'context_id', 'checked_at'],
					'project_snapshot' => ['project_id', 'id'],
					'collect' => ['status', 'next_check_at'],
					'provider_task' => ['provider_task_id'],
					'run' => ['run_id', 'status'],
					'market_task' => ['market_task_id'],
				],
			],
			'serp_results' => [
				'columns' => [
					'snapshot_id' => 'int unsigned',
					'item_index' => 'smallint unsigned',
					'result_type' => 'tinyint unsigned',
					'rank_group' => 'smallint unsigned',
					'rank_absolute' => 'smallint unsigned',
					'page' => 'tinyint unsigned',
					'domain_id' => 'int unsigned',
					'url_id' => 'int unsigned',
					'snippet_id' => 'int unsigned',
					'flags' => 'smallint unsigned',
				],
				'primary' => ['snapshot_id', 'item_index'],
				'unique' => [],
				'indexes' => ['domain_snapshot' => ['domain_id', 'snapshot_id', 'rank_group']],
			],
			'serp_domains' => [
				'columns' => [
					'id' => 'int unsigned',
					'host_hash' => 'binary(16)',
					'host' => 'varchar(253)',
					'host_rev' => 'varchar(253)',
					'created_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['host_hash' => ['host_hash']],
				'indexes' => ['host_rev' => ['host_rev']],
			],
			'serp_urls' => [
				'columns' => [
					'id' => 'int unsigned',
					'url_hash' => 'binary(16)',
					'domain_id' => 'int unsigned',
					'url' => 'varchar(2048)',
					'created_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['url_hash' => ['url_hash']],
				'indexes' => ['domain' => ['domain_id']],
			],
			'serp_snippets' => [
				'columns' => [
					'id' => 'int unsigned',
					'snippet_hash' => 'binary(16)',
					'title' => 'varchar(512)',
					'description' => 'text',
					'breadcrumb' => 'varchar(512)',
					'website_name' => 'varchar(255)',
					'extra' => 'longtext',
					'created_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['snippet_hash' => ['snippet_hash']],
				'indexes' => [],
			],
			'gap_domains' => [
				'columns' => [
					'id' => 'int unsigned',
					'provider' => 'varchar(20)',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'domain' => 'varchar(253)',
					'domain_key' => 'binary(16)',
					'status' => "enum('empty','importing','ready','partial')",
					'coverage_max_rank' => 'tinyint unsigned',
					'coverage_min_volume' => 'int unsigned',
					'coverage_max_rows' => 'int unsigned',
					'complete' => 'tinyint unsigned',
					'covered_min_volume' => 'int unsigned',
					'total_count' => 'int unsigned',
					'rows_present' => 'int unsigned',
					'labs_updated_at' => 'datetime',
					'import_run_id' => 'int unsigned',
					'imported_at' => 'datetime',
					'stale_after' => 'datetime',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['market_domain' => ['provider', 'location_code', 'language_code', 'domain_key']],
				'indexes' => [],
			],
			'gap_domain_keywords' => [
				'columns' => [
					'domain_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'rank_group' => 'tinyint unsigned',
					'rank_absolute' => 'smallint unsigned',
					'url_id' => 'int unsigned',
					'etv' => 'decimal(12,2)',
					'serp_on' => 'date',
					'first_seen' => 'date',
					'last_seen' => 'date',
					'seen_run_id' => 'int unsigned',
					'prev_rank' => 'tinyint unsigned',
					'changed_on' => 'date',
					'present' => 'tinyint unsigned',
				],
				'primary' => ['domain_id', 'market_keyword_id'],
				'unique' => [],
				'indexes' => ['domain_url' => ['domain_id', 'url_id', 'rank_group']],
			],
			'gap_domain_events' => [
				'columns' => [
					'domain_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'run_id' => 'int unsigned',
					'event' => "enum('new','lost','back','url','up','down')",
					'rank_old' => 'tinyint unsigned',
					'rank_new' => 'tinyint unsigned',
					'url_old' => 'int unsigned',
					'url_new' => 'int unsigned',
					'observed_on' => 'date',
				],
				'primary' => ['domain_id', 'market_keyword_id', 'run_id', 'event'],
				'unique' => [],
				'indexes' => ['domain_run' => ['domain_id', 'run_id']],
			],
			'gap_runs' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'provider' => 'varchar(20)',
					'location_code' => 'int unsigned',
					'language_code' => 'varchar(10)',
					'status' => "enum('queued','running','paused','completed','partial','failed','cancelled')",
					'trigger_type' => 'varchar(16)',
					'max_rank' => 'tinyint unsigned',
					'min_volume' => 'int unsigned',
					'max_rows' => 'int unsigned',
					'forced' => 'tinyint unsigned',
					'targets_planned' => 'smallint unsigned',
					'targets_done' => 'smallint unsigned',
					'requests_planned' => 'int unsigned',
					'requests_done' => 'int unsigned',
					'estimated_cost' => 'decimal(12,6)',
					'cost' => 'decimal(12,6)',
					'rows_received' => 'int unsigned',
					'blocked_by' => 'varchar(32)',
					'error_code' => 'varchar(64)',
					'error_message' => 'varchar(255)',
					'active_project_id' => 'int unsigned',
					'created_by' => 'bigint unsigned',
					'created_at' => 'datetime',
					'started_at' => 'datetime',
					'paused_at' => 'datetime',
					'finished_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'active_project' => ['active_project_id']],
				'indexes' => ['project_run' => ['project_id', 'id'], 'status_run' => ['status', 'id']],
			],
			'gap_run_targets' => [
				'columns' => [
					'run_id' => 'int unsigned',
					'domain_id' => 'int unsigned',
					'role' => "enum('competitor','project')",
					'competitor_id' => 'int unsigned',
					'position' => 'smallint unsigned',
					'status' => "enum('pending','cached','running','done','partial','failed','cancelled')",
					'next_offset' => 'int unsigned',
					'pages_done' => 'smallint unsigned',
					'total_count' => 'int unsigned',
					'rows_received' => 'int unsigned',
					'rows_unique' => 'int unsigned',
					'rows_new' => 'int unsigned',
					'rows_lost' => 'int unsigned',
					'rows_changed' => 'int unsigned',
					'last_volume' => 'int unsigned',
					'inflight_task_id' => 'bigint unsigned',
					'estimated_cost' => 'decimal(12,6)',
					'cost' => 'decimal(12,6)',
					'attempts' => 'tinyint unsigned',
					'error_code' => 'varchar(64)',
					'next_attempt_at' => 'datetime',
					'stats' => 'longtext',
					'started_at' => 'datetime',
					'finished_at' => 'datetime',
				],
				'primary' => ['run_id', 'domain_id'],
				'unique' => [],
				'indexes' => ['domain_finished' => ['domain_id', 'finished_at']],
			],
			'gap_settings' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'competitor_max_rank' => 'tinyint unsigned',
					'min_volume' => 'int unsigned',
					'max_difficulty' => 'tinyint unsigned',
					'fetch_max_rank' => 'tinyint unsigned',
					'fetch_min_volume' => 'int unsigned',
					'max_rows' => 'int unsigned',
					'include_terms' => 'text',
					'brand_terms' => 'text',
					'refresh_days' => 'smallint unsigned',
					'schedule_enabled' => 'tinyint unsigned',
					'schedule_enabled_at' => 'datetime',
					'schedule_enabled_by' => 'bigint unsigned',
					'next_refresh_at' => 'datetime',
					'last_skip_reason' => 'varchar(32)',
					'last_skip_at' => 'datetime',
					'data_key' => 'binary(16)',
					'recalculated_at' => 'datetime',
					'updated_by' => 'bigint unsigned',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id'],
				'unique' => [],
				'indexes' => [],
			],
			'gap_keywords' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'market_keyword_id' => 'int unsigned',
					'status' => "enum('new','review','accepted','dismissed')",
					'note' => 'text',
					'status_changed_at' => 'datetime',
					'status_changed_by' => 'bigint unsigned',
					'active' => 'tinyint unsigned',
					'listed' => 'tinyint unsigned',
					'filter_reason' => 'varchar(24)',
					'gap_type' => "enum('missing','weak','competitive','stronger','unknown')",
					'visibility' => "enum('unknown','none','low','visible')",
					'visibility_source' => "enum('serp','gsc','labs')",
					'sporadic' => 'tinyint unsigned',
					'project_position' => 'decimal(6,2)',
					'project_labs_rank' => 'tinyint unsigned',
					'serp_rank' => 'smallint unsigned',
					'serp_checked_at' => 'datetime',
					'gsc_impressions' => 'int unsigned',
					'gsc_clicks' => 'int unsigned',
					'gsc_position' => 'decimal(6,2)',
					'competitors_count' => 'tinyint unsigned',
					'competitors_top10' => 'tinyint unsigned',
					'best_competitor_id' => 'int unsigned',
					'best_competitor_rank' => 'tinyint unsigned',
					'best_url_id' => 'int unsigned',
					'search_volume' => 'int unsigned',
					'keyword_difficulty' => 'tinyint unsigned',
					'cpc' => 'decimal(12,4)',
					'intent' => 'varchar(16)',
					'content_gap' => "enum('improve','new_page','unclear','covered')",
					'cluster_id' => 'int unsigned',
					'target_url_id' => 'int unsigned',
					'target_source' => "enum('serp','gsc','labs','slug')",
					'priority' => 'tinyint unsigned',
					'score' => 'longtext',
					'evidence_on' => 'date',
					'first_seen_at' => 'datetime',
					'scored_at' => 'datetime',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id'], 'project_market_keyword' => ['project_id', 'market_keyword_id']],
				'indexes' => [
					'project_list' => ['project_id', 'listed', 'gap_type', 'priority'],
					'project_volume' => ['project_id', 'listed', 'search_volume'],
					'project_cluster' => ['project_id', 'cluster_id'],
				],
			],
			'gap_clusters' => [
				'columns' => [
					'id' => 'int unsigned',
					'public_id' => 'char(26)',
					'project_id' => 'int unsigned',
					'leader_market_keyword_id' => 'int unsigned',
					'label' => 'varchar(255)',
					'label_key' => 'binary(16)',
					'active' => 'tinyint unsigned',
					'keywords_count' => 'int unsigned',
					'gap_keywords_count' => 'int unsigned',
					'total_volume' => 'int unsigned',
					'gap_volume' => 'int unsigned',
					'competitors_count' => 'tinyint unsigned',
					'best_competitor_id' => 'int unsigned',
					'best_competitor_rank' => 'tinyint unsigned',
					'competitor_pages' => 'smallint unsigned',
					'dedicated_pages' => 'smallint unsigned',
					'visibility' => "enum('unknown','none','low','visible')",
					'content_gap' => "enum('improve','new_page','unclear','covered')",
					'content_reason' => 'varchar(32)',
					'confidence' => "enum('low','medium','high')",
					'target_url_id' => 'int unsigned',
					'target_source' => "enum('serp','gsc','labs','slug')",
					'priority' => 'tinyint unsigned',
					'status' => "enum('new','review','accepted','dismissed')",
					'note' => 'text',
					'status_changed_at' => 'datetime',
					'status_changed_by' => 'bigint unsigned',
					'first_seen_at' => 'datetime',
					'created_at' => 'datetime',
					'updated_at' => 'datetime',
				],
				'primary' => ['id'],
				'unique' => ['public_id' => ['public_id']],
				'indexes' => ['project_list' => ['project_id', 'active', 'content_gap', 'priority']],
			],
			'gap_competitor_pages' => [
				'columns' => [
					'project_id' => 'int unsigned',
					'competitor_id' => 'int unsigned',
					'url_id' => 'int unsigned',
					'url_key' => 'binary(16)',
					'title' => 'varchar(512)',
					'page_type' => 'tinyint unsigned',
					'keywords' => 'int unsigned',
					'top3' => 'int unsigned',
					'top10' => 'int unsigned',
					'top20' => 'int unsigned',
					'total_volume' => 'int unsigned',
					'etv' => 'decimal(14,2)',
					'gap_keywords' => 'int unsigned',
					'gap_volume' => 'int unsigned',
					'overlap_keywords' => 'int unsigned',
					'main_intent' => 'varchar(16)',
					'best_rank' => 'tinyint unsigned',
					'best_market_keyword_id' => 'int unsigned',
					'cluster_id' => 'int unsigned',
					'updated_at' => 'datetime',
				],
				'primary' => ['project_id', 'competitor_id', 'url_id'],
				'unique' => [],
				'indexes' => ['project_gap' => ['project_id', 'gap_keywords'], 'project_url' => ['project_id', 'url_key']],
			],
		];
	}

	/**
	 * Normalizacja typu z information_schema: MariaDB/MySQL 5.7 zwracają `int(10) unsigned`,
	 * MySQL 8 — `int unsigned`.
	 */
	public static function normalizeType(string $type): string
	{
		$type = strtolower(trim($type));

		return (string) preg_replace('/^(tinyint|smallint|mediumint|int|bigint)\(\d+\)/', '$1', $type);
	}
}
